export const SET_CURR_USER = 'SET_CURR_USER';
export const SET_CHOSEN_CHAT = 'SET_CHOSEN_CHAT';
export const SET_MENU_TOGGLE = 'SET_MENU_TOGGLE';
export const SET_CREATE_CHAT_TOGGLE = 'SET_CREATE_CHAT_TOGGLE';
export const ADD_ITEM_TO_USER_CHAT_LIST = 'ADD_ITEM_TO_USER_CHAT_LIST';
export const SET_CHATS_LIST = 'SET_CHATS_LIST';
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN';